### ISSUE TITLE
Making this work in Linux.

### ISSUE THREAD

**Issue by TijuanaKez** [jtydhr88/ComfyUI-LayerDivider#13] opened 2024-06-27 00:32 UTC
Love the Layer Divider, loath Windows.

Would love to make the node work on my Ubuntu machine I have setup specifically for AI tasks.
Trying to work out how to make it work without using the included .bat files.

Does absolutely require Python 3.11?
Looking at your readme and the bat files it seems it want to create it's own python environment and install python 3.11 there, but I dont see how that can work as ComfyUI parent folder already has it's own pyenv with Python 3.10 installed and this environment has to activated to run ComfyUI. All the other custom nodes use this environment.

Can you give a bit more explanation?

Thanks.

**Comment by jtydhr88** [comment] 2024-06-27 02:07
hi, 
First, I don't think it depends on Python 3.11 only . 
However I choose Python 3.11 because the release ComfyUI embedded Python 3.11 as default, see from release page https://github.com/comfyanonymous/ComfyUI/releases, and I only work it out on this version of ComfyUI,

However, since this repo depends on some speical packages, such as pytoshop, if we want to make this repo on other envs matrix, for example, py311-linux, py310-linux and py310-win, we need to make this dependency packages have correct version for them.

Regarding to pytoshop, it only has py310-win provided officially, so I built py311-win by my self, and provided in https://github.com/jtydhr88/ComfyUI-LayerDivider/tree/master/_Pre_Builds/_Wheels_win_py311_cu121.

Since I don't have Linux locally, I am not sure it has compatibility to py310-linux or py311-linux.

**Comment by TijuanaKez** [comment] 2024-06-27 02:31
Thanks for the quick reply.
Ok that looks like a specific windows build. 
Cloning the ComfyUI repo and installing requirements etc gave me Python 3.10.12 inside its venv.
I'm ahead of recommended CUDA as it worked better for some things, and therefore torch,
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4   
Torch Version: 2.4.0.dev20240526+cu124

Everything else works great though and very fast on 3090.

I'm happy to compile pytoshop etc if needed.

I'm fairly new to python so I hit a brick wall here. I get ''Miss dependencies' due to NODE_CLASS_MAPPINGS
But I dont really know how to determine which particularly dependencies would cause it to fail.

```
NODE_CLASS_MAPPINGS = {
    "LayerDivider - Color Base": LayerDividerColorBase,
    "LayerDivider - Load SAM Mask Generator": LayerDividerLoadMaskGenerator,
    "LayerDivider - Segment Mask": LayerDividerSegmentMask,
    "LayerDivider - Divide Layer": LayerDividerDivideLayer
}

```


Thanks.

**Comment by jtydhr88** [comment] 2024-06-27 03:02
I think the issue is https://github.com/jtydhr88/ComfyUI-LayerDivider/issues/1 which I might need to setup a local Linux to investigate it...

**Comment by jtydhr88** [comment] 2024-07-05 03:07
![image](https://github.com/jtydhr88/ComfyUI-LayerDivider/assets/860985/a3bfe6e2-adf4-4442-9717-6646e65f43fe)
just make it working on Linux, the code is ok, but require some setting up, I will update doc soon

**Comment by jtydhr88** [comment] 2024-07-06 01:39
I update the readme, and to run this repo in Linux, the key steps:
- pip install cython
- pip install pytoshop -I --no-cache-dir
- pip install psd_tools
- pip install onnxruntime-gpu==1.17.0 --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
make sure run them one by one.
Close this issue

**Closed by jtydhr88** 2024-07-06 01:39 UTC
